const USER_TYPES = {
  LOGIN: 'LOGIN',
  LOGIN_CHECK: 'LOGIN_CHECK',
  LOG_OUT: 'LOG_OUT',
  GET_USERS: 'GET_USERS',
  SIGNUP: 'SIGNUP',
  LEAVE_REVIEW: 'LEAVE_REVIEW',
  GET_REVIEWS: 'GET_REVIEWS',
};

export default USER_TYPES;
